server:
  port: 8083

# 与dataID 环境前的name一致 alibaba-nacos-config-dev.properties
spring:
  application:
    name: alibaba-nacos-config
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: test
